# Auto-generated by generate_pipeline.py

text_content = """
### 1. What is A* Search Algorithm?
➔ A* is an informed search algorithm that efficiently finds the shortest path between a starting node and a target node in a graph by combining features of Dijkstra's algorithm and Greedy Best-First Search.

### 2. Explanation:
A* works by intelligently exploring a graph to find the optimal path. It does this by evaluating each potential step (node) using a function `f(n) = g(n) + h(n)`.
*   `g(n)` represents the actual cost from the starting node to the current node `n`. This is the "past cost" or "cost so far."
*   `h(n)` is a heuristic function that estimates the cost from the current node `n` to the goal node. This is the "future cost" or "estimated cost to go." For A* to guarantee finding the *shortest* path, `h(n)` must be "admissible" (never overestimates the true cost) and often "consistent" (monotonically non-decreasing along any path).
*   `f(n)` is the total estimated cost of the path through node `n` to the goal. A* always prioritizes exploring the node with the lowest `f(n)` value, making it a "best-first" search.

The algorithm maintains two lists to manage its search:
1.  **Open List (or Frontier):** A priority queue containing nodes that have been visited but not yet fully explored (i.e., their neighbors haven't all been processed). These are candidates for the next step, ordered by their `f(n)` value.
2.  **Closed List:** A set containing nodes that have already been fully explored. Once a node is in the closed list, A* won't revisit it unless a significantly better path to it is found (which typically doesn't happen with consistent heuristics).

A* starts at the initial node, adds it to the open list, and then repeatedly:
1.  Selects the node `n` from the open list with the lowest `f(n)`.
2.  If `n` is the goal, the path is found, and the algorithm terminates.
3.  Otherwise, `n` is moved from the open list to the closed list.
4.  It then generates all of `n`'s neighbors. For each neighbor:
    *   If the neighbor is in the closed list, ignore it.
    *   Calculate `g(neighbor)` (current `g(n)` + cost from `n` to `neighbor`).
    *   If the neighbor is not in the open list, or if the new `g(neighbor)` is lower than its previously recorded `g` value:
        *   Update its `g` value.
        *   Calculate its `f` value (`g(neighbor) + h(neighbor)`).
        *   Set `n` as its parent (for path reconstruction).
        *   Add it to the open list (or update its position if already there).

This process continues until the goal node is reached or the open list becomes empty (meaning no path exists).

### 3. Example:
Let's find the shortest path from 'S' (Start) to 'G' (Goal) on a simple 4x4 grid.
Movement cost: 1 for horizontal/vertical moves. Diagonal moves not allowed.
Heuristic `h(n)`: Manhattan distance to the goal (G).

Grid:
```text
S . . .
. X . .
. . . .
. . . G
```
Coordinates: S=(0,0), G=(3,3). 'X' is an obstacle at (1,1).

**Step 0: Initialize**
*   Open List: `[]`
*   Closed List: `[]`
*   `g(S)` = 0
*   `h(S)` = Manhattan distance from (0,0) to (3,3) = |3-0| + |3-0| = 3 + 3 = 6
*   `f(S)` = `g(S)` + `h(S)` = 0 + 6 = 6
*   Add `(f=6, S)` to Open List.
Open List: `[(f=6, S)]`

**Step 1: Expand S (0,0)**
*   Pop `S` (f=6) from Open List. Add `S` to Closed List.
*   Neighbors of `S` (0,0): (0,1) and (1,0).

    *   **Neighbor (0,1):**
        *   `g(0,1)` = `g(S)` + cost(S to (0,1)) = 0 + 1 = 1
        *   `h(0,1)` = |3-0| + |3-1| = 3 + 2 = 5
        *   `f(0,1)` = `g(0,1)` + `h(0,1)` = 1 + 5 = 6
        *   Parent: `S`. Add `(f=6, (0,1))` to Open List.
    *   **Neighbor (1,0):**
        *   `g(1,0)` = `g(S)` + cost(S to (1,0)) = 0 + 1 = 1
        *   `h(1,0)` = |3-1| + |3-0| = 2 + 3 = 5
        *   `f(1,0)` = `g(1,0)` + `h(1,0)` = 1 + 5 = 6
        *   Parent: `S`. Add `(f=6, (1,0))` to Open List.

*   Open List: `[(f=6, (0,1)), (f=6, (1,0))]` (Order might vary, assume (0,1) is picked next due to tie-breaking)
*   Closed List: `[S]`

**Step 2: Expand (0,1)**
*   Pop `(0,1)` (f=6) from Open List. Add `(0,1)` to Closed List.
*   Neighbors of `(0,1)`: `(0,0)` (in Closed), `(0,2)`, `(1,1)`.

    *   **Neighbor (0,2):**
        *   `g(0,2)` = `g(0,1)` + cost((0,1) to (0,2)) = 1 + 1 = 2
        *   `h(0,2)` = |3-0| + |3-2| = 3 + 1 = 4
        *   `f(0,2)` = `g(0,2)` + `h(0,2)` = 2 + 4 = 6
        *   Parent: `(0,1)`. Add `(f=6, (0,2))` to Open List.
    *   **Neighbor (1,1):** This is an obstacle 'X'. Ignore it.

*   Open List: `[(f=6, (1,0)), (f=6, (0,2))]` (Assume (1,0) is picked next)
*   Closed List: `[S, (0,1)]`

**Step 3: Expand (1,0)**
*   Pop `(1,0)` (f=6) from Open List. Add `(1,0)` to Closed List.
*   Neighbors of `(1,0)`: `(0,0)` (in Closed), `(2,0)`, `(1,1)`.

    *   **Neighbor (2,0):**
        *   `g(2,0)` = `g(1,0)` + cost((1,0) to (2,0)) = 1 + 1 = 2
        *   `h(2,0)` = |3-2| + |3-0| = 1 + 3 = 4
        *   `f(2,0)` = `g(2,0)` + `h(2,0)` = 2 + 4 = 6
        *   Parent: `(1,0)`. Add `(f=6, (2,0))` to Open List.
    *   **Neighbor (1,1):** This is an obstacle 'X'. Ignore it.

*   Open List: `[(f=6, (0,2)), (f=6, (2,0))]` (Assume (0,2) is picked next)
*   Closed List: `[S, (0,1), (1,0)]`

... The algorithm continues, always picking the node with the lowest `f` value. It will explore nodes like (0,2), (2,0), (0,3), (1,3), (2,3), (3,3).

**Later Step: Reaching the Goal**
Suppose the algorithm has processed nodes and `(2,3)` is currently the node with the lowest `f` value in the Open List.
*   `g(2,3)` = 5 (e.g., S -> (1,0) -> (2,0) -> (2,1) -> (2,2) -> (2,3) - path cost 5)
*   `h(2,3)` = |3-2| + |3-3| = 1 + 0 = 1
*   `f(2,3)` = 5 + 1 = 6

*   Pop `(2,3)` (f=6) from Open List. Add `(2,3)` to Closed List.
*   Neighbors of `(2,3)`: `(1,3)`, `(3,3)` (Goal!), `(2,2)` (already processed/in Open).

    *   **Neighbor (3,3) (Goal G):**
        *   `g(3,3)` = `g(2,3)` + cost((2,3) to (3,3)) = 5 + 1 = 6
        *   `h(3,3)` = |3-3| + |3-3| = 0 + 0 = 0
        *   `f(3,3)` = `g(3,3)` + `h(3,3)` = 6 + 0 = 6
        *   Parent: `(2,3)`. Add `(f=6, G)` to Open List.

*   Now, `G` (3,3) is in the Open List with `f=6`. Since it has the lowest `f`-value (or is tied), it will be chosen next.
*   Pop `G` (f=6) from Open List.
*   `G` is the goal node. Algorithm terminates.

Path Reconstruction (by backtracking parent pointers):
`G (3,3)` <- `(2,3)` <- `(2,2)` <- `(2,1)` <- `(2,0)` <- `(1,0)` <- `S (0,0)`
Final Path: S -> (1,0) -> (2,0) -> (2,1) -> (2,2) -> (2,3) -> G
Total Cost: 6

### 4. Algorithm Logic:
```python
import heapq # For priority queue implementation

def a_star_search(start_node, goal_node, graph, heuristic_function):
    '''
    Finds the shortest path between start_node and goal_node using A* algorithm.

    Args:
        start_node: The starting node.
        goal_node: The target node.
        graph: A graph object with methods:
               - get_neighbors(node): Returns a list of neighbor nodes.
               - get_edge_cost(node1, node2): Returns the cost to move between two nodes.
               - nodes: A list or set of all nodes in the graph.
        heuristic_function: A function h(node, goal) that estimates the cost
                            from node to goal.
    Returns:
        A list representing the path from start_node to goal_node, or None if no path exists.
    '''

    # g_score: cost from start to current node
    # f_score: g_score + h_score (estimated total cost)
    g_score = {node: float('inf') for node in graph.nodes}
    f_score = {node: float('inf') for node in graph.nodes}
    parent = {} # To reconstruct the path

    # Initialize start node
    g_score[start_node] = 0
    f_score[start_node] = heuristic_function(start_node, goal_node)

    # Open list is a priority queue storing (f_score, node)
    open_list = [(f_score[start_node], start_node)]
    
    # Closed list stores nodes that have been fully evaluated
    closed_list = set()

    while open_list:
        # Get the node with the lowest f_score from the open list
        current_f, current_node = heapq.heappop(open_list)

        if current_node == goal_node:
            return reconstruct_path(parent, current_node) # Path found!

        # If we've already processed this node with a better or equal path, skip it
        if current_node in closed_list:
            continue

        closed_list.add(current_node)

        for neighbor in graph.get_neighbors(current_node):
            # If the neighbor is already in the closed list, ignore it
            if neighbor in closed_list:
                continue

            # Calculate tentative g_score for the neighbor
            # This is the cost from start to current_node + cost from current_node to neighbor
            tentative_g_score = g_score[current_node] + graph.get_edge_cost(current_node, neighbor)

            # If this path to neighbor is better than any previous one, record it
            if tentative_g_score < g_score[neighbor]:
                parent[neighbor] = current_node
                g_score[neighbor] = tentative_g_score
                f_score[neighbor] = g_score[neighbor] + heuristic_function(neighbor, goal_node)
                
                # Add or update the neighbor in the open list
                # heapq.heappush handles duplicates; the one with lower f_score will be processed first.
                heapq.heappush(open_list, (f_score[neighbor], neighbor))

    return None # No path found

def reconstruct_path(parent_map, current_node):
    '''Reconstructs the path from the start node to the current_node.'''
    path = [current_node]
    while current_node in parent_map:
        current_node = parent_map[current_node]
        path.append(current_node)
    return path[::-1] # Reverse to get path from start to goal
```

### 5. Uses and real-world implementations:
A* is a widely used algorithm due to its efficiency and optimality guarantees (with an admissible heuristic).

*   **Video Game AI (Pathfinding):** Used extensively in games for non-player characters (NPCs) to navigate game worlds, find routes to targets, or avoid obstacles. This is crucial in genres like real-time strategy (RTS), role-playing games (RPGs), and even first-person shooters for enemy movement.
*   **Robotics (Motion Planning):** Robots use A* to plan collision-free paths in complex, dynamic environments. This applies to industrial robots in manufacturing, autonomous vehicles navigating city streets, and even drones performing aerial inspections.
*   **Logistics and Transportation (Route Optimization):** Finding the shortest or fastest routes for delivery services (e.g., Amazon, UPS), ride-sharing apps (e.g., Uber, Lyft), and public transportation networks, considering factors like traffic, road closures, and travel time.
"""

canvas_payload = """
# TODO: Insert raw code or Three.js script here
"""

def get_astar_content():
    return {
        "title": "A* Search Algorithm",
        "text_explanation": text_content,
        "media_type": "python_code",
        "code": canvas_payload
    }
