# Auto-generated by generate_pipeline.py

text_content = """
### 1. What is Dijkstra's Algorithm?
➔ Dijkstra's Algorithm is a greedy algorithm used to find the shortest paths between nodes in a graph, specifically from a single source node to all other nodes, where edge weights are non-negative.

### 2. Explanation:
Imagine you're trying to find the quickest route from your starting point to various destinations on a map, where each road segment has a specific travel time (its "weight"). Dijkstra's Algorithm works by systematically exploring the graph, always prioritizing the unvisited path that currently appears to be the shortest.

It starts at your designated "source" node and assigns it a distance of zero. All other nodes initially have an "infinite" distance. The algorithm then repeatedly performs these steps:
1.  **Select the "closest" unvisited node:** From all the nodes it hasn't finalized yet, it picks the one with the smallest known distance from the source.
2.  **"Relax" its neighbors:** For this selected node, it looks at all its direct connections (neighbors). For each neighbor, it calculates if going through the selected node would offer a shorter path to that neighbor than what's currently known. If a shorter path is found, it updates the neighbor's distance and records that the selected node is now the best "previous" step to reach that neighbor.
3.  **Mark as visited:** Once a node has been selected and its neighbors' distances updated, its shortest path from the source is considered final and it's marked as "visited" (or "settled").

This process continues until all reachable nodes have been visited, guaranteeing that when a node is marked as visited, the distance recorded for it is indeed the shortest possible from the source.

### 3. Example:
Let's find the shortest paths from node **A** to all other nodes in the following graph:

```text
Graph:
    A --4-- B
    |       |
    2       3
    |       |
    C --2-- D --1-- E
    \     /
     5   (direct path from C to E)

Initial State (Distances from A, Previous Node):
Node | Distance | Previous
-----|----------|---------
A    | 0        | -
B    | ∞        | -
C    | ∞        | -
D    | ∞        | -
E    | ∞        | -
Unvisited: {A, B, C, D, E}

Step 1: Select A (current_node = A, dist = 0) - Smallest distance in Unvisited.
  - Neighbors of A: B (weight 4), C (weight 2)
  - Update B: dist[B] = min(∞, 0 + 4) = 4, prev[B] = A
  - Update C: dist[C] = min(∞, 0 + 2) = 2, prev[C] = A
  - Mark A as visited.

Current State:
Node | Distance | Previous
-----|----------|---------
A    | 0        | -
B    | 4        | A
C    | 2        | A
D    | ∞        | -
E    | ∞        | -
Unvisited: {B, C, D, E}

Step 2: Select C (current_node = C, dist = 2) - Smallest distance in Unvisited.
  - Neighbors of C: D (weight 2), E (weight 5)
  - Update D: dist[D] = min(∞, 2 + 2) = 4, prev[D] = C
  - Update E: dist[E] = min(∞, 2 + 5) = 7, prev[E] = C
  - Mark C as visited.

Current State:
Node | Distance | Previous
-----|----------|---------
A    | 0        | -
B    | 4        | A
C    | 2        | A
D    | 4        | C
E    | 7        | C
Unvisited: {B, D, E}

Step 3: Select B (current_node = B, dist = 4) - Smallest distance in Unvisited (tied with D, pick B arbitrarily).
  - Neighbors of B: E (weight 3)
  - Update E: dist[E] = min(7, 4 + 3) = 7 (no change), prev[E] remains C
  - Mark B as visited.

Current State:
Node | Distance | Previous
-----|----------|---------
A    | 0        | -
B    | 4        | A
C    | 2        | A
D    | 4        | C
E    | 7        | C
Unvisited: {D, E}

Step 4: Select D (current_node = D, dist = 4) - Smallest distance in Unvisited.
  - Neighbors of D: E (weight 1)
  - Update E: dist[E] = min(7, 4 + 1) = 5, prev[E] = D
  - Mark D as visited.

Current State:
Node | Distance | Previous
-----|----------|---------
A    | 0        | -
B    | 4        | A
C    | 2        | A
D    | 4        | C
E    | 5        | D
Unvisited: {E}

Step 5: Select E (current_node = E, dist = 5) - Smallest distance in Unvisited.
  - No unvisited neighbors.
  - Mark E as visited.

Final State:
Node | Distance | Previous
-----|----------|---------
A    | 0        | -
B    | 4        | A
C    | 2        | A
D    | 4        | C
E    | 5        | D

Shortest path from A to E: A -> C -> D -> E (total distance 5).
```

### 4. Algorithm Logic:

```python
function Dijkstra(graph, source_node):
    # Initialize distances:
    #   - distance to source_node is 0
    #   - distance to all other nodes is infinity
    distances = {node: infinity for node in graph.nodes}
    distances[source_node] = 0

    # To reconstruct the shortest path
    previous_nodes = {node: None for node in graph.nodes}

    # Priority queue stores (distance, node) pairs, ordered by distance
    # We use a min-heap for efficient extraction of the smallest distance
    priority_queue = [(0, source_node)] # (initial_distance, initial_node)

    # Set to keep track of visited nodes (optional, but can optimize)
    visited = set()

    while priority_queue:
        # Extract the node 'u' with the smallest distance from the priority queue
        current_distance, current_node = extract_min(priority_queue)

        # If we've already found a shorter path to current_node and processed it, skip
        if current_node in visited:
            continue

        # Mark current_node as visited
        visited.add(current_node)

        # Iterate over all neighbors 'v' of the current_node
        for neighbor, weight in graph.get_neighbors(current_node):
            # Calculate the distance to the neighbor through the current_node
            distance_through_current = current_distance + weight

            # If this new path is shorter than the currently known shortest path to neighbor
            if distance_through_current < distances[neighbor]:
                distances[neighbor] = distance_through_current
                previous_nodes[neighbor] = current_node
                # Add (or update) the neighbor in the priority queue
                insert(priority_queue, (distance_through_current, neighbor))
    
    return distances, previous_nodes # distances to all nodes, and paths to reconstruct them
```

### 5. Uses and real-world implementations:
*   **GPS Navigation Systems:** Finding the **shortest (or fastest) route** between two locations on a map, considering traffic conditions or road types as edge weights.
*   **Network Routing Protocols:** Used in protocols like **OSPF (Open Shortest Path First)** to determine the most efficient path for data packets to travel across a computer network, minimizing latency or hop count.
*   **Logistics and Delivery Services:** Optimizing **delivery routes for vehicles** to minimize travel time, fuel consumption, or distance for package delivery, ride-sharing, or emergency services.
"""

canvas_payload = """
# TODO: Insert raw code or Three.js script here
"""

def get_dijkstra_content():
    return {
        "title": "Dijkstra's Algorithm",
        "text_explanation": text_content,
        "media_type": "python_code",
        "code": canvas_payload
    }
