# Auto-generated by generate_pipeline.py

text_content = """
### 1. What is Greedy Algorithms Algorithm?
➔ Greedy algorithms make the locally optimal choice at each stage with the hope of finding a global optimum.

### 2. Explanation:
A greedy algorithm works by making a series of choices. At each step, it picks the best immediate option available without considering the long-term consequences of that choice. It doesn't look ahead to see if a slightly worse immediate choice might lead to a much better overall solution. Instead, it focuses solely on maximizing or minimizing the current step's outcome. This "take what you can get now" approach makes greedy algorithms often simpler and faster than other optimization techniques, but it doesn't always guarantee the absolute best (globally optimal) solution. However, for many problems, a greedy strategy does yield the optimal solution, or at least a very good approximation.

### 3. Example:
Let's consider a **Smart Stock Replenishment System** for a retail store with a limited budget. The goal is to maximize the potential profit from restocking items.

**Scenario:**
You have a budget of **$30** to restock items. Each item has a specific cost and a projected profit if sold. Your greedy strategy is to prioritize items that offer the highest **profit per dollar spent** until your budget runs out.

**Available Items for Replenishment:**

```text
---------------------------------------------------
| Item | Cost ($) | Profit ($) |
---------------------------------------------------
| A    | 10       | 5          |
| B    | 20       | 12         |
| C    | 5        | 2          |
| D    | 15       | 9          |
| E    | 8        | 4.8        |
---------------------------------------------------
```

**Step-by-step Trace:**

1.  **Initial State:**
    ```text
    Budget: $30
    Selected Items for Replenishment: []
    Total Projected Profit: $0
    ```

2.  **Calculate Profit/Cost Ratio for each item:**
    This ratio helps us determine which item gives the most profit for each dollar invested.
    ```text
    ---------------------------------------------------
    | Item | Cost ($) | Profit ($) | Profit/Cost Ratio |
    ---------------------------------------------------
    | A    | 10       | 5          | 0.5  (5/10)       |
    | B    | 20       | 12         | 0.6  (12/20)      |
    | C    | 5        | 2          | 0.4  (2/5)        |
    | D    | 15       | 9          | 0.6  (9/15)       |
    | E    | 8        | 4.8        | 0.6  (4.8/8)      |
    ---------------------------------------------------
    ```

3.  **Sort Items by Profit/Cost Ratio (descending):**
    (Assuming tie-breaking by item name for items with the same ratio)
    ```text
    ---------------------------------------------------
    | Item | Cost ($) | Profit ($) | Profit/Cost Ratio |
    ---------------------------------------------------
    | B    | 20       | 12         | 0.6               |
    | D    | 15       | 9          | 0.6               |
    | E    | 8        | 4.8        | 0.6               |
    | A    | 10       | 5          | 0.5               |
    | C    | 5        | 2          | 0.4               |
    ---------------------------------------------------
    ```

4.  **Greedy Selection Process:**

    *   **Consider Item B (Ratio 0.6):**
        *   Current Budget: $30
        *   Item B Cost: $20
        *   Can we afford it? Yes ($30 >= $20).
        *   **Action:** Replenish Item B.
        ```text
        Budget: $30 - $20 = $10
        Selected Items: [Item B]
        Total Projected Profit: $0 + $12 = $12
        ```

    *   **Consider Item D (Ratio 0.6):**
        *   Current Budget: $10
        *   Item D Cost: $15
        *   Can we afford it? No ($10 < $15).
        *   **Action:** Skip Item D.

    *   **Consider Item E (Ratio 0.6):**
        *   Current Budget: $10
        *   Item E Cost: $8
        *   Can we afford it? Yes ($10 >= $8).
        *   **Action:** Replenish Item E.
        ```text
        Budget: $10 - $8 = $2
        Selected Items: [Item B, Item E]
        Total Projected Profit: $12 + $4.8 = $16.8
        ```

    *   **Consider Item A (Ratio 0.5):**
        *   Current Budget: $2
        *   Item A Cost: $10
        *   Can we afford it? No ($2 < $10).
        *   **Action:** Skip Item A.

    *   **Consider Item C (Ratio 0.4):**
        *   Current Budget: $2
        *   Item C Cost: $5
        *   Can we afford it? No ($2 < $5).
        *   **Action:** Skip Item C.

5.  **Final Result:**
    No more items can be replenished with the remaining budget.
    ```text
    Final Budget Remaining: $2
    Items Replenished: [Item B, Item E]
    Total Projected Profit from Replenishment: $16.8
    ```
    By making locally optimal choices (picking the item with the best profit/cost ratio at each step), the system maximizes the immediate profit given the budget constraint.

### 4. Algorithm Logic:

```python
def smart_stock_replenishment(items, budget):
    '''
    Optimizes stock replenishment using a greedy approach based on profit per unit cost.

    Args:
        items (list of dict): Each dict represents an item with 'name', 'cost', 'profit'.
        budget (float): The total budget available for replenishment.

    Returns:
        tuple: A tuple containing the list of selected items and the total profit generated.
    '''

    # 1. Calculate profit_per_cost ratio for each item
    #    and store it along with the item details.
    items_with_ratios = []
    for item in items:
        if item['cost'] > 0:
            profit_per_cost = item['profit'] / item['cost']
        else:
            profit_per_cost = float('inf') # Handle free items or items with no cost
        items_with_ratios.append({
            'name': item['name'],
            'cost': item['cost'],
            'profit': item['profit'],
            'profit_per_cost': profit_per_cost
        })

    # 2. Sort items based on profit_per_cost ratio in descending order.
    #    This is the greedy choice: prioritize items that yield the most profit per dollar.
    items_with_ratios.sort(key=lambda x: x['profit_per_cost'], reverse=True)

    selected_items = []
    total_profit = 0.0
    current_budget = budget

    # 3. Iterate through the sorted items and select them if affordable.
    for item in items_with_ratios:
        if current_budget >= item['cost']:
            selected_items.append(item['name'])
            current_budget -= item['cost']
            total_profit += item['profit']
        # If the current item cannot be afforded, we stop because subsequent items
        # (which have lower or equal profit_per_cost ratios) might also not be affordable
        # or we might not have enough budget to combine them effectively.
        # This is a simple greedy approach for the knapsack-like problem.
        # For fractional knapsack, we could take parts of items.
        # For 0/1 knapsack (which this is), this greedy choice is not always optimal
        # but is a common greedy heuristic.
        # In this specific stock replenishment context, it's a practical heuristic.

    return selected_items, total_profit

# Example Usage (as per the trace above):
# items_data = [
#     {'name': 'A', 'cost': 10, 'profit': 5},
#     {'name': 'B', 'cost': 20, 'profit': 12},
#     {'name': 'C', 'cost': 5, 'profit': 2},
#     {'name': 'D', 'cost': 15, 'profit': 9},
#     {'name': 'E', 'cost': 8, 'profit': 4.8},
# ]
# replenishment_budget = 30
# selected, profit = smart_stock_replenishment(items_data, replenishment_budget)
# print(f"Selected items: {selected}")
# print(f"Total profit: ${profit}")
```

### 5. Uses and real-world implementations:

*   **Minimum Spanning Tree Algorithms (Prim's and Kruskal's):** Used in network design to find the cheapest way to connect a set of nodes (e.g., laying fiber optic cables to connect cities) by iteratively choosing the locally cheapest edge that doesn't form a cycle.
*   **Dijkstra's Shortest Path Algorithm:** Finds the shortest path between two nodes in a graph with non-negative edge weights (e.g., GPS navigation systems finding the quickest route) by always extending the path through the unvisited neighbor with the smallest cumulative distance.
*   **Huffman Coding (Data Compression):** Used in file compression (like JPEG, MP3, ZIP) to create variable-length codes for characters, where more frequent characters get shorter codes, by repeatedly merging the two least frequent symbols.
"""

canvas_payload = """
# TODO: Insert raw code or Three.js script here
"""

def get_greedy_content():
    return {
        "title": "Greedy Algorithms",
        "text_explanation": text_content,
        "media_type": "python_code",
        "code": canvas_payload
    }
