# Auto-generated by generate_pipeline.py

text_content = """
### 1. What is Solar System?
➔ The Solar System is a gravitationally bound system comprising the Sun and everything that orbits it, including planets, dwarf planets, moons, asteroids, comets, and dust.

### 2. Planets:
*   **Mercury:** The smallest and innermost planet, Mercury is a rocky world with an extremely thin atmosphere and dramatic temperature swings between its sunlit and shadowed sides. Its surface is heavily cratered, resembling Earth's Moon, due to billions of years of impacts.
*   **Venus:** Often called Earth's "sister planet" due to its similar size, Venus is shrouded in a thick, toxic atmosphere of carbon dioxide, leading to a runaway greenhouse effect and surface temperatures hot enough to melt lead. It rotates slowly in the opposite direction to most planets.
*   **Earth:** Our home planet, Earth is unique for its abundant liquid water, a diverse biosphere, and a protective atmosphere that sustains life. It possesses a strong magnetic field and a single large moon, playing a crucial role in stabilizing its axial tilt.
*   **Mars:** Known as the "Red Planet" due to iron oxides on its surface, Mars is a cold, desert world with a thin atmosphere. Evidence suggests it once had liquid water flowing across its surface, and it hosts polar ice caps and the largest volcano in the Solar System, Olympus Mons.
*   **Jupiter:** The largest planet, Jupiter is a gas giant primarily composed of hydrogen and helium, famous for its Great Red Spot, a colossal storm larger than Earth that has raged for centuries. It possesses a powerful magnetic field and a complex system of rings and numerous moons, including the four Galilean moons.
*   **Saturn:** Renowned for its magnificent and intricate system of icy rings, Saturn is another gas giant, less dense than water. It has a yellowish hue and a vast family of moons, with Titan being the second-largest moon in the Solar System and the only one with a dense atmosphere.
*   **Uranus:** An ice giant, Uranus has a blue-green appearance due to methane in its atmosphere and is unique for rotating on its side, almost perpendicular to its orbital plane. It has a faint ring system and a collection of icy moons.
*   **Neptune:** The farthest known planet, Neptune is a deep blue ice giant with powerful winds and dynamic storm systems, including the historical Great Dark Spot. It has a faint ring system and a large moon, Triton, which orbits in a retrograde direction.

### 3. Other entities:
*   **Asteroids:** Rocky, airless remnants left over from the early formation of our Solar System, ranging in size from pebbles to hundreds of kilometers across. Most are found in the main asteroid belt between Mars and Jupiter.
*   **Comets:** Icy, dusty bodies that originate from the outer reaches of the Solar System. When they approach the Sun, their ice vaporizes, creating a glowing coma and often a spectacular tail of gas and dust stretching millions of kilometers.
*   **Dwarf Planets:** Celestial bodies that orbit the Sun, are massive enough to be spherical due to their own gravity, but have not cleared their orbital neighborhood of other debris. Examples include Pluto, Eris, Ceres, Makemake, and Haumea.
*   **Kuiper Belt:** A vast ring of icy bodies extending beyond Neptune's orbit, home to dwarf planets like Pluto and Eris, and a source of short-period comets. It is a relic from the early Solar System's formation.
*   **Oort Cloud:** A theoretical spherical shell of icy objects believed to envelop the Solar System at distances up to 100,000 AU from the Sun, serving as the primary reservoir for long-period comets. It is thought to be a remnant of the Sun's protoplanetary disk.
*   **Interstellar Objects:** Objects that originate from outside our Solar System and travel through interstellar space before briefly passing through our Sun's gravitational influence. 'Oumuamua and 2I/Borisov are the only confirmed examples.
*   **Sun:** The star at the center of our Solar System, a yellow dwarf that accounts for over 99.8% of the system's total mass. Its immense gravitational pull holds the planets in orbit, and its nuclear fusion provides the light and heat essential for life on Earth.

### 4. Key Facts & Numbers:
*   The Sun accounts for 99.86% of the Solar System's total mass, making it gravitationally dominant over everything else.
*   If you could drive a car to the Sun at 100 km/h, it would take you over 170 years to reach it.
*   The Oort Cloud, the outermost region of our Solar System, is estimated to extend up to 100,000 Astronomical Units (AU), meaning it could take light over 1.5 years to cross it.
*   Jupiter's Great Red Spot is a storm larger than Earth that has been raging for at least 350 years, showcasing the immense scale and longevity of planetary phenomena.

### 5. Importance and Exploration:
*   **Voyager 1 & 2:** These twin probes, launched in 1977, have explored the outer planets and are now the only human-made objects to have entered interstellar space, providing unprecedented data about the heliosphere and beyond.
*   **Mars Rovers (e.g., Perseverance, Curiosity):** A series of highly successful robotic missions that have extensively explored the Martian surface, searching for signs of past life, analyzing geology, and preparing for future human exploration.
*   **Cassini-Huygens:** An ambitious mission to Saturn and its moons, operating from 2004 to 2017, which revolutionized our understanding of Saturn's rings, its atmosphere, and its moon Titan, even landing a probe on Titan's surface.
"""

canvas_payload = """
# TODO: Insert raw code or Three.js script here
"""

def get_solar_content():
    return {
        "title": "The Solar System",
        "text_explanation": text_content,
        "media_type": "3D_simulation",
        "code": canvas_payload
    }
