# backend/generate_pipeline.py

import os
import asyncio
from langchain_core.prompts import ChatPromptTemplate
from services.llm_client import gemini_llm

os.makedirs("Cards", exist_ok=True)

# ==========================================
# 1. SET YOUR TARGET HERE
# Options: "dijkstra", "astar", "greedy", "solar"
# ==========================================
CURRENT_TARGET = "solar"

# ==========================================
# 2. TEMPLATES
# ==========================================
SPACE_TEMPLATE = """You are an expert astronomer. 
Generate a comprehensive explanation for: {topic}.

You MUST strictly follow this exact Markdown structure:
### 1. What is Solar System?
➔ [One sentence definition]

### 2. Planets:
[Give 2-3 line description of each planet]

### 3. Other entities:
[Give 2-3 line description of each of the following: Asteroids, Comets, Dwarf Planets, Kuiper Belt, Oort Cloud, Interstellar Objects, Sun]

### 4. Key Facts & Numbers:
[Provide 3-4 mind-blowing statistics in bullet points]

### 5. Importance and Exploration:
[List 3 specific historical or ongoing space missions related to this topic as bullet points in bold]"""


# ==========================================
# 3. TOPIC DATA
# ==========================================
TOPICS = {
    "dijkstra": {
        "name": "Dijkstra's Algorithm",
        "type": "algorithm",
        "filename": "Cards/dijkastraAlgo.py",
        "func_name": "get_dijkstra_content",
        "extra_context": ""
    },
    "astar": {
        "name": "A* Search Algorithm",
        "type": "algorithm",
        "filename": "Cards/astarAlgo.py",
        "func_name": "get_astar_content",
        "extra_context": ""
    },
    "greedy": {
        "name": "Greedy Algorithms",
        "type": "algorithm",
        "filename": "Cards/greedyAlgo.py",
        "func_name": "get_greedy_content",
        "extra_context": "Highlight a Smart Stock Replenishment System as a core real-world example, explaining how it optimizes stock by making locally optimal choices based on sales and profit data."
    },
    "solar": {
        "name": "The Solar System",
        "type": "space",
        "filename": "Cards/Solar.py",
        "func_name": "get_solar_content",
        "extra_context": ""
    }
}

# ==========================================
# 4. GENERATOR LOGIC
# ==========================================
async def generate_single_card():
    topic_data = TOPICS[CURRENT_TARGET]
    print(f"Generating content for {topic_data['name']}...")
    
    template_str = ALGORITHM_TEMPLATE if topic_data["type"] == "algorithm" else SPACE_TEMPLATE
    prompt = ChatPromptTemplate.from_template(template_str)
    
    chain = prompt | gemini_llm
    
    response = await chain.ainvoke({
        "topic": topic_data["name"],
        "extra_context": topic_data.get("extra_context", "")
    })
    
    generated_markdown = getattr(response, 'content', str(response))
    safe_markdown = generated_markdown.replace('"""', "'''")

    media_type = "python_code" if topic_data["type"] == "algorithm" else "3D_simulation"
    
    py_file_content = f"""# Auto-generated by generate_pipeline.py

text_content = \"\"\"
{safe_markdown}
\"\"\"

canvas_payload = \"\"\"
# TODO: Insert raw code or Three.js script here
\"\"\"

def {topic_data['func_name']}():
    return {{
        "title": "{topic_data['name']}",
        "text_explanation": text_content,
        "media_type": "{media_type}",
        "code": canvas_payload
    }}
"""

    with open(topic_data["filename"], "w", encoding="utf-8") as f:
        f.write(py_file_content)
        
    print(f"✅ Successfully created {topic_data['filename']}! Go check it.")

if __name__ == "__main__":
    asyncio.run(generate_single_card())