import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

// ═══════════════════════════════════════════════════════════════
//  PLANET DATA CATALOGUE
//  orbitSpeed is a scaled analogue of linear orbital velocity.
//  It gets divided by orbitRadius in the animation loop to derive
//  angular velocity, approximating Kepler's 3rd law: T² ∝ a³
//  (outer planets complete fewer revolutions per unit time).
// ═══════════════════════════════════════════════════════════════
const PLANET_DATA = [
  {
    name: 'Mercury',
    radius: 0.75,
    color: 0x9e9e9e,
    accent: 0x6d6d6d,
    emissive: 0x1a1a1a,
    orbitRadius: 11,
    orbitSpeed: 4.74,
    rotationSpeed: 0.004,
    tilt: 0.034,
    bands: false, rings: false, hasCloud: false,
    mass: '3.30 × 10²³ kg',
    distance: '57.9 million km',
    fact: 'Mercury has no atmosphere, causing temperatures to swing from −180°C at night to 430°C by day — the largest range of any planet.',
  },
  {
    name: 'Venus',
    radius: 1.45,
    color: 0xe8c97c,
    accent: 0xc4a050,
    emissive: 0x201200,
    orbitRadius: 17,
    orbitSpeed: 3.50,
    rotationSpeed: -0.002,    // negative = retrograde spin
    tilt: 177.4,
    bands: false, rings: false, hasCloud: true,
    mass: '4.87 × 10²⁴ kg',
    distance: '108.2 million km',
    fact: 'Venus spins backwards and so slowly that a Venusian day (243 Earth days) is longer than its year (225 Earth days).',
  },
  {
    name: 'Earth',
    radius: 1.6,
    color: 0x2b7de9,
    accent: 0x1a4a80,
    emissive: 0x061020,
    orbitRadius: 24,
    orbitSpeed: 2.98,
    rotationSpeed: 0.01,
    tilt: 23.4,
    bands: false, rings: false, hasCloud: true,
    mass: '5.97 × 10²⁴ kg',
    distance: '149.6 million km',
    fact: "Earth's magnetic field, generated by its liquid iron core, deflects lethal solar wind and is fundamental to all life on the surface.",
  },
  {
    name: 'Mars',
    radius: 1.1,
    color: 0xc0411a,
    accent: 0x7a2200,
    emissive: 0x1a0800,
    orbitRadius: 33,
    orbitSpeed: 2.41,
    rotationSpeed: 0.0097,
    tilt: 25.2,
    bands: false, rings: false, hasCloud: false,
    mass: '6.42 × 10²³ kg',
    distance: '227.9 million km',
    fact: 'Olympus Mons on Mars is the tallest volcano in the Solar System at 21.9 km — nearly three times the height of Mount Everest.',
  },
  {
    name: 'Jupiter',
    radius: 4.5,
    color: 0xc8924a,
    accent: 0x8a5a28,
    emissive: 0x120800,
    orbitRadius: 56,
    orbitSpeed: 1.31,
    rotationSpeed: 0.04,
    tilt: 3.1,
    bands: true, rings: false, hasCloud: false,
    mass: '1.90 × 10²⁷ kg',
    distance: '778.5 million km',
    fact: "Jupiter's Great Red Spot is an anticyclone wider than Earth itself that has been raging continuously for over 350 years.",
  },
  {
    name: 'Saturn',
    radius: 3.8,
    color: 0xe4d08a,
    accent: 0xb09a50,
    emissive: 0x141000,
    orbitRadius: 78,
    orbitSpeed: 0.97,
    rotationSpeed: 0.038,
    tilt: 26.7,
    bands: true, rings: true, hasCloud: false,
    mass: '5.68 × 10²⁶ kg',
    distance: '1.43 billion km',
    fact: "Saturn's density (0.687 g/cm³) is lower than water — it would float in a sufficiently large ocean. Its rings span 282,000 km yet are only ~10–100 m thick.",
  },
  {
    name: 'Uranus',
    radius: 2.5,
    color: 0x7de8e0,
    accent: 0x3aa8a0,
    emissive: 0x081818,
    orbitRadius: 98,
    orbitSpeed: 0.68,
    rotationSpeed: -0.025,    // retrograde
    tilt: 97.8,
    bands: false, rings: false, hasCloud: true,
    mass: '8.68 × 10²⁵ kg',
    distance: '2.87 billion km',
    fact: "Uranus has an axial tilt of 97.8° and essentially rolls around the Sun on its side — likely the result of a massive ancient collision.",
  },
  {
    name: 'Neptune',
    radius: 2.35,
    color: 0x3a5be0,
    accent: 0x1a2a8a,
    emissive: 0x040820,
    orbitRadius: 118,
    orbitSpeed: 0.54,
    rotationSpeed: 0.032,
    tilt: 28.3,
    bands: false, rings: false, hasCloud: false,
    mass: '1.02 × 10²⁶ kg',
    distance: '4.50 billion km',
    fact: 'Neptune has the fastest sustained winds in the Solar System — up to 2,100 km/h — despite receiving only 1/900th the sunlight Earth does.',
  },
];

// ═══════════════════════════════════════════════════════════════
//  PROCEDURAL TEXTURE GENERATOR
//  Builds a 512×256 canvas texture entirely in JavaScript.
//  - bands=true  → horizontal atmospheric belt stripes + Great Red Spot
//  - Surface noise dots add micro-variation on all bodies
//  This replaces every external texture file with generated data.
// ═══════════════════════════════════════════════════════════════
function createProceduralTexture(baseHex, accentHex, bands = false) {
  const W = 512, H = 256;
  const canvas = document.createElement('canvas');
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');

  // Clamp & convert a 24-bit hex integer to a CSS "#rrggbb" string
  const toCSS = n => '#' + Math.max(0, Math.min(0xffffff, n)).toString(16).padStart(6, '0');

  // Latitudinal gradient — slightly darker at poles, brighter at equator
  const grad = ctx.createLinearGradient(0, 0, 0, H);
  grad.addColorStop(0.0, toCSS(accentHex - 0x151510));
  grad.addColorStop(0.35, toCSS(baseHex));
  grad.addColorStop(0.65, toCSS(baseHex));
  grad.addColorStop(1.0, toCSS(accentHex - 0x151510));
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, W, H);

  if (bands) {
    // Render 14 atmospheric belt stripes at random opacity/width
    for (let i = 0; i < 14; i++) {
      const y     = (i / 14) * H + (Math.random() - 0.5) * 6;
      const bH    = (Math.random() * 0.06 + 0.015) * H;
      const alpha = Math.random() * 0.25 + 0.08;
      // Alternate between warm brown and pale cream tones
      const r = i % 2 === 0 ? 160 + Math.random() * 40 : 220 + Math.random() * 30;
      const g = i % 2 === 0 ?  90 + Math.random() * 30 : 190 + Math.random() * 20;
      const b = 30 + Math.random() * 20;
      ctx.fillStyle = `rgba(${r|0},${g|0},${b|0},${alpha.toFixed(2)})`;
      ctx.fillRect(0, y, W, bH);
    }

    // Great Red Spot — a radial gradient ellipse centred below the equator
    const sx = W * 0.62, sy = H * 0.57;
    const srx = W * 0.068, sry = H * 0.072;
    const sg = ctx.createRadialGradient(sx, sy, 0, sx, sy, srx);
    sg.addColorStop(0,   'rgba(200,60,30,0.85)');
    sg.addColorStop(0.6, 'rgba(170,50,20,0.50)');
    sg.addColorStop(1,   'rgba(150,40,10,0.00)');
    ctx.save();
    ctx.scale(1, sry / srx);          // squash circle into ellipse
    ctx.beginPath();
    ctx.arc(sx, sy * (srx / sry), srx, 0, Math.PI * 2);
    ctx.fillStyle = sg;
    ctx.fill();
    ctx.restore();
  }

  // Surface noise: 600 tiny bright/dark dots for micro-texture
  for (let i = 0; i < 600; i++) {
    const x = Math.random() * W, y = Math.random() * H;
    ctx.beginPath();
    ctx.arc(x, y, Math.random() * 1.5, 0, Math.PI * 2);
    ctx.fillStyle = Math.random() > 0.5
      ? `rgba(255,255,255,${(Math.random() * 0.06).toFixed(3)})`
      : `rgba(0,0,0,${(Math.random() * 0.07).toFixed(3)})`;
    ctx.fill();
  }

  return new THREE.CanvasTexture(canvas);
}

// ═══════════════════════════════════════════════════════════════
//  STARFIELD
//  8,000 particles uniformly distributed on a sphere of radius
//  550–700 using spherical coordinates. Each star gets a spectral
//  colour: warm yellow-white, cool blue-white, or neutral white.
// ═══════════════════════════════════════════════════════════════
function createStarfield() {
  const N   = 8000;
  const geo = new THREE.BufferGeometry();
  const pos = new Float32Array(N * 3);
  const col = new Float32Array(N * 3);

  for (let i = 0; i < N; i++) {
    // Uniform sphere distribution via inverse-CDF on cos(phi)
    const theta = Math.random() * Math.PI * 2;
    const phi   = Math.acos(2 * Math.random() - 1);
    const r     = 550 + Math.random() * 150;

    pos[i * 3]     = r * Math.sin(phi) * Math.cos(theta);
    pos[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta);
    pos[i * 3 + 2] = r * Math.cos(phi);

    const t = Math.random(); // spectral class selector
    col[i * 3]     = t < 0.3 ? 1.00 : t < 0.6 ? 0.85 : 0.95;  // R
    col[i * 3 + 1] = t < 0.3 ? 0.92 : t < 0.6 ? 0.90 : 0.95;  // G
    col[i * 3 + 2] = t < 0.3 ? 0.70 : t < 0.6 ? 1.00 : 1.00;  // B
  }

  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  geo.setAttribute('color',    new THREE.BufferAttribute(col, 3));

  const mat = new THREE.PointsMaterial({
    size: 0.45, vertexColors: true,
    sizeAttenuation: true, transparent: true, opacity: 0.90,
  });

  return new THREE.Points(geo, mat);
}

// ═══════════════════════════════════════════════════════════════
//  ORBITAL PATH
//  EllipseCurve (actually circular here) sampled at 128 points
//  and projected onto the XZ plane as a looping THREE.Line.
// ═══════════════════════════════════════════════════════════════
function createOrbitPath(radius) {
  const curve  = new THREE.EllipseCurve(0, 0, radius, radius, 0, Math.PI * 2, false, 0);
  const points = curve.getPoints(128).map(p => new THREE.Vector3(p.x, 0, p.y));
  const geo    = new THREE.BufferGeometry().setFromPoints(points);
  const mat    = new THREE.LineBasicMaterial({ color: 0x3a4466, transparent: true, opacity: 0.35 });
  return new THREE.Line(geo, mat);
}

// ═══════════════════════════════════════════════════════════════
//  SATURN RINGS
//  RingGeometry with manually-corrected radial UVs and a canvas
//  gradient texture that fades to transparent at both edges.
// ═══════════════════════════════════════════════════════════════
function createSaturnRings(planetRadius) {
  const inner = planetRadius * 1.45;
  const outer = planetRadius * 2.5;
  const geo   = new THREE.RingGeometry(inner, outer, 80);

  // Remap UVs so u ∈ [0,1] = radial distance from inner→outer ring edge.
  // Three.js RingGeometry defaults to a flat XY UV mapping which
  // doesn't work well with a radial gradient texture.
  const position = geo.attributes.position;
  const uv       = geo.attributes.uv;
  for (let i = 0; i < position.count; i++) {
    const x = position.getX(i), y = position.getY(i);
    const r = Math.sqrt(x * x + y * y);
    uv.setXY(i, (r - inner) / (outer - inner), 0.5);
  }

  // Canvas gradient: transparent → bright band → transparent
  const rc   = document.createElement('canvas');
  rc.width = 256; rc.height = 1;
  const cx = rc.getContext('2d');
  const rg = cx.createLinearGradient(0, 0, 256, 0);
  rg.addColorStop(0.00, 'rgba(180,160, 80,0.00)');
  rg.addColorStop(0.10, 'rgba(200,180,100,0.60)');
  rg.addColorStop(0.35, 'rgba(220,200,120,0.85)');
  rg.addColorStop(0.60, 'rgba(180,160, 80,0.50)');
  rg.addColorStop(0.80, 'rgba(200,180,100,0.70)');
  rg.addColorStop(1.00, 'rgba(160,140, 60,0.00)');
  cx.fillStyle = rg;
  cx.fillRect(0, 0, 256, 1);
  const ringTex = new THREE.CanvasTexture(rc);

  const mat   = new THREE.MeshBasicMaterial({
    map: ringTex, side: THREE.DoubleSide,
    transparent: true, depthWrite: false,
  });
  const rings = new THREE.Mesh(geo, mat);
  rings.rotation.x = Math.PI / 2.1; // slight off-axis tilt for realism
  return rings;
}

// ═══════════════════════════════════════════════════════════════
//  SUN
//  MeshStandardMaterial with high emissive intensity + two
//  translucent shell spheres for an inner halo and diffuse corona.
// ═══════════════════════════════════════════════════════════════
function createSun() {
  const geo = new THREE.SphereGeometry(6, 64, 64);
  const mat = new THREE.MeshStandardMaterial({
    color: 0xffdd33, emissive: 0xff8800,
    emissiveIntensity: 1.5, roughness: 0.75, metalness: 0.0,
  });
  const sun = new THREE.Mesh(geo, mat);

  // Inner halo — BackSide so it's visible from outside
  sun.add(new THREE.Mesh(
    new THREE.SphereGeometry(6.8, 32, 32),
    new THREE.MeshBasicMaterial({ color: 0xff6600, transparent: true, opacity: 0.08, side: THREE.BackSide }),
  ));

  // Outer diffuse corona
  sun.add(new THREE.Mesh(
    new THREE.SphereGeometry(8.5, 32, 32),
    new THREE.MeshBasicMaterial({ color: 0xff4400, transparent: true, opacity: 0.035, side: THREE.BackSide }),
  ));

  return sun;
}

// ═══════════════════════════════════════════════════════════════
//  INFO OVERLAY (planet detail card)
//  Always appended to containerElement — never to document.body.
// ═══════════════════════════════════════════════════════════════
function buildOverlay(container) {
  const el = document.createElement('div');
  Object.assign(el.style, {
    position: 'absolute', bottom: '28px', right: '28px', width: '310px',
    background: 'linear-gradient(145deg,rgba(4,8,24,0.97) 0%,rgba(8,16,50,0.95) 100%)',
    border: '1px solid rgba(100,160,255,0.28)', borderRadius: '16px',
    padding: '20px 22px', color: '#ccd8ff',
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    fontSize: '13px', lineHeight: '1.65',
    boxShadow: '0 0 40px rgba(40,80,255,0.18), 0 8px 32px rgba(0,0,0,0.6)',
    backdropFilter: 'blur(14px)', zIndex: '10', display: 'none',
    transition: 'opacity 0.35s ease, transform 0.35s ease',
    pointerEvents: 'auto', transform: 'translateY(12px)',
  });
  container.appendChild(el);
  return el;
}

// ═══════════════════════════════════════════════════════════════
//  SPEED CONTROL HUD
//  A range slider in the top-left corner; 0× pauses, 5× is max.
// ═══════════════════════════════════════════════════════════════
function buildSpeedHud(container, setSpeed) {
  const hud = document.createElement('div');
  Object.assign(hud.style, {
    position: 'absolute', top: '20px', left: '20px',
    background: 'rgba(4,8,24,0.82)',
    border: '1px solid rgba(100,160,255,0.22)',
    borderRadius: '10px', padding: '10px 16px', color: '#8aabdd',
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    fontSize: '12px', zIndex: '10',
    backdropFilter: 'blur(10px)', userSelect: 'none',
  });
  hud.innerHTML = `
    <div style="margin-bottom:6px;letter-spacing:.06em;text-transform:uppercase;font-size:10px;color:#5578aa;">
      ⏱ Simulation Speed
    </div>
    <div style="display:flex;align-items:center;gap:10px;">
      <input id="sol-speed" type="range" min="0" max="5" step="0.1" value="1"
        style="width:120px;accent-color:#4488ff;cursor:pointer;">
      <span id="sol-speed-lbl" style="color:#aaccff;min-width:28px;">1.0×</span>
    </div>
    <div style="margin-top:8px;font-size:10px;color:#3a5588;">
      Click a planet · Drag to orbit · Scroll to zoom
    </div>`;
  container.appendChild(hud);
  hud.querySelector('#sol-speed').addEventListener('input', (e) => {
    const v = parseFloat(e.target.value);
    setSpeed(v);
    hud.querySelector('#sol-speed-lbl').textContent = `${v.toFixed(1)}×`;
  });
  return hud;
}

// ═══════════════════════════════════════════════════════════════
//  MAIN EXPORT
// ═══════════════════════════════════════════════════════════════
/**
 * initSolarSystem(containerElement)
 *
 * Initialises a complete Three.js Solar System scene and mounts it
 * entirely within `containerElement`. The renderer canvas, HTML overlay
 * panels, and all DOM event listeners are scoped to that element only.
 *
 * @param   {HTMLElement} containerElement
 * @returns {() => void}  cleanup — call on React unmount to free all resources
 */
export function initSolarSystem(containerElement) {

  // Overlays use position:absolute so the container must be non-static.
  if (getComputedStyle(containerElement).position === 'static') {
    containerElement.style.position = 'relative';
  }

  // ── Scene ──────────────────────────────────────────────────────
  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x020408);
  // Exponential fog to naturaliy fade distant orbit rings
  scene.fog = new THREE.FogExp2(0x020408, 0.0012);

  // ── Camera ─────────────────────────────────────────────────────
  const W = containerElement.clientWidth;
  const H = containerElement.clientHeight;
  const camera = new THREE.PerspectiveCamera(55, W / H, 0.1, 2000);
  camera.position.set(0, 65, 140);
  camera.lookAt(0, 0, 0);

  // ── Renderer ───────────────────────────────────────────────────
  const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); // cap at 2× for mobile perf
  renderer.setSize(W, H);
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type    = THREE.PCFSoftShadowMap;
  renderer.toneMapping       = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 0.85;
  containerElement.appendChild(renderer.domElement);

  // ── Lighting ───────────────────────────────────────────────────
  // Low ambient so planet night sides remain visibly dark
  scene.add(new THREE.AmbientLight(0x111133, 0.55));

  // The Sun is the sole significant light source — a PointLight at the origin
  const sunLight = new THREE.PointLight(0xfff5e0, 3.8, 600, 1.2);
  sunLight.position.set(0, 0, 0);
  sunLight.castShadow = true;
  sunLight.shadow.mapSize.set(2048, 2048);
  sunLight.shadow.bias = -0.0001;
  scene.add(sunLight);

  // ── Starfield ──────────────────────────────────────────────────
  const starfield = createStarfield();
  scene.add(starfield);

  // ── Sun ────────────────────────────────────────────────────────
  const sun = createSun();
  scene.add(sun);

  // ── Planets ────────────────────────────────────────────────────
  /**
   * Hierarchy per planet:
   *
   *   scene
   *     └─ pivot   (Object3D — Y-rotated for orbital motion)
   *           └─ mesh    (Sphere   — Y-rotated for self-spin)
   *                 ├─ wireframe overlay  (adds surface grid detail)
   *                 ├─ cloud shell        (Earth / Venus only)
   *                 └─ ring system        (Saturn only)
   *
   * Separating orbital rotation (pivot) from axial rotation (mesh)
   * avoids gimbal lock and keeps the math straightforward.
   */
  const planetObjects = [];  // { data, pivot, mesh }
  const disposables   = [];  // all THREE resources to .dispose() on cleanup

  PLANET_DATA.forEach((data) => {
    // Procedural canvas texture — no file I/O required
    const tex = createProceduralTexture(data.color, data.accent, data.bands);
    disposables.push(tex);

    const geo = new THREE.SphereGeometry(data.radius, 56, 56);
    const mat = new THREE.MeshStandardMaterial({
      map: tex,
      emissive: new THREE.Color(data.emissive),
      emissiveIntensity: 0.12,
      roughness: 0.88,
      metalness: 0.0,
    });
    disposables.push(geo, mat);

    const mesh = new THREE.Mesh(geo, mat);
    mesh.castShadow    = true;
    mesh.receiveShadow = true;
    mesh.rotation.z    = THREE.MathUtils.degToRad(data.tilt); // cosmetic axial tilt

    // userData carries all planet metadata for the raycaster info panel
    mesh.userData = { ...data, isPlanet: true };

    // Subtle wireframe shell — adds a grid detail layer at near-zero cost
    const wGeo = new THREE.SphereGeometry(data.radius + 0.01, 28, 28);
    const wMat = new THREE.MeshBasicMaterial({ color: data.color, wireframe: true, transparent: true, opacity: 0.03 });
    disposables.push(wGeo, wMat);
    mesh.add(new THREE.Mesh(wGeo, wMat));

    // Cloud shell for Earth and Venus
    if (data.hasCloud) {
      const cGeo = new THREE.SphereGeometry(data.radius + 0.08, 48, 48);
      const cMat = new THREE.MeshStandardMaterial({ color: 0xffffff, transparent: true, opacity: 0.22, depthWrite: false, roughness: 1.0 });
      disposables.push(cGeo, cMat);
      const clouds = new THREE.Mesh(cGeo, cMat);
      clouds.userData.isCloud = true;
      mesh.add(clouds);
    }

    // Saturn ring system
    if (data.rings) {
      const rings = createSaturnRings(data.radius);
      disposables.push(rings.geometry, rings.material, rings.material.map);
      mesh.add(rings);
    }

    // Orbit pivot: position planet at its orbital radius along +X
    const pivot = new THREE.Object3D();
    mesh.position.set(data.orbitRadius, 0, 0);
    pivot.add(mesh);
    scene.add(pivot);

    // Visible orbit ring (flat line on XZ plane)
    const orbitLine = createOrbitPath(data.orbitRadius);
    disposables.push(orbitLine.geometry, orbitLine.material);
    scene.add(orbitLine);

    // Randomise starting longitude so all planets aren't bunched together at t=0
    pivot.rotation.y = Math.random() * Math.PI * 2;

    planetObjects.push({ data, pivot, mesh });
  });

  // ── OrbitControls ──────────────────────────────────────────────
  const controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.055;
  controls.minDistance   = 8;    // prevents zooming inside the Sun
  controls.maxDistance   = 380;  // prevents flying off into deep space
  controls.zoomSpeed     = 1.1;
  controls.rotateSpeed   = 0.55;
  controls.enablePan     = true;
  controls.panSpeed      = 0.8;

  // ── Raycaster ──────────────────────────────────────────────────
  const raycaster  = new THREE.Raycaster();
  raycaster.params.Points.threshold = 0.3;
  const pointer    = new THREE.Vector2();
  // Only test top-level planet meshes (children like cloud/wire are hit recursively)
  const rayTargets = planetObjects.map(p => p.mesh);

  // ── UI Overlays ────────────────────────────────────────────────
  const overlay  = buildOverlay(containerElement);
  let   simSpeed = 1.0;
  const speedHud = buildSpeedHud(containerElement, v => { simSpeed = v; });

  // ── Camera Focus Animation State ───────────────────────────────
  /**
   * Clicking a planet begins a ~1.4 s smooth camera flyby toward it.
   * We record the camera's position and OrbitControls target at the
   * moment of click, then lerp both toward the planet over focusProgress
   * [0 → 1] using a cubic ease-in-out curve. Pressing "Close" triggers
   * the reverse flyby back to the default overview.
   *
   * OrbitControls is disabled during the flyby so user input doesn't fight it.
   */
  let focusTarget   = null;   // { data, pivot, mesh } | null
  let isFocusing    = false;
  let focusProgress = 0;      // 0.0 → 1.0
  const camFrom     = new THREE.Vector3();
  const tgtFrom     = new THREE.Vector3();
  const OVERVIEW_POS = new THREE.Vector3(0, 65, 140);
  const OVERVIEW_TGT = new THREE.Vector3(0,  0,   0);

  /** Cubic ease-in-out: smooth acceleration and deceleration. */
  function easeInOutCubic(t) {
    return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
  }

  function startFocusFlyby(planetObj) {
    focusTarget = planetObj; isFocusing = true; focusProgress = 0;
    camFrom.copy(camera.position);
    tgtFrom.copy(controls.target);
    controls.enabled = false;
  }

  function returnToOverview() {
    focusTarget = null; isFocusing = true; focusProgress = 0;
    camFrom.copy(camera.position);
    tgtFrom.copy(controls.target);
    controls.enabled = false;
    overlay.style.opacity   = '0';
    overlay.style.transform = 'translateY(12px)';
    setTimeout(() => { overlay.style.display = 'none'; }, 360);
  }

  // ── Planet Info Card ───────────────────────────────────────────
  function showPlanetInfo(d) {
    overlay.innerHTML = `
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;">
        <span style="font-size:18px;font-weight:700;color:#88b8ff;letter-spacing:.05em;">✦ ${d.name}</span>
        <button id="sol-close" style="background:rgba(80,120,255,0.14);border:1px solid rgba(80,120,255,0.35);
          color:#88b8ff;border-radius:8px;padding:3px 11px;cursor:pointer;font-size:12px;">✕ Close</button>
      </div>
      <hr style="border:none;border-top:1px solid rgba(80,120,255,0.2);margin-bottom:14px;">
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:12px;">
        <div style="background:rgba(30,50,120,0.3);border-radius:8px;padding:9px 11px;">
          <div style="color:#4d70aa;font-size:10px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:3px;">Mass</div>
          <div style="color:#dce8ff;font-size:12px;">${d.mass}</div>
        </div>
        <div style="background:rgba(30,50,120,0.3);border-radius:8px;padding:9px 11px;">
          <div style="color:#4d70aa;font-size:10px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:3px;">Dist. from Sun</div>
          <div style="color:#dce8ff;font-size:12px;">${d.distance}</div>
        </div>
      </div>
      <div style="background:rgba(40,60,160,0.18);border-left:2px solid rgba(80,120,255,0.5);
                  border-radius:0 8px 8px 0;padding:10px 13px;">
        <div style="color:#4d70aa;font-size:10px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px;">🔭 Fun Fact</div>
        <div style="color:#c4d6ff;font-style:italic;font-size:12.5px;">${d.fact}</div>
      </div>`;
    overlay.style.display = 'block';
    // Trigger CSS entry transition: start shifted+hidden, then reveal
    requestAnimationFrame(() => {
      overlay.style.opacity   = '1';
      overlay.style.transform = 'translateY(0)';
    });
    overlay.querySelector('#sol-close').addEventListener('click', returnToOverview);
  }

  // ── Pointer / Raycast Handler ──────────────────────────────────
  function onPointerDown(e) {
    if (e.button !== 0) return; // left-click only
    const rect = renderer.domElement.getBoundingClientRect();
    // Map pixel coordinates to NDC [-1,1] × [-1,1]
    pointer.x =  ((e.clientX - rect.left) / rect.width)  * 2 - 1;
    pointer.y = -((e.clientY - rect.top)  / rect.height) * 2 + 1;

    raycaster.setFromCamera(pointer, camera);
    // recursive=true tests child meshes (cloud shells, wireframes, rings)
    const hits = raycaster.intersectObjects(rayTargets, true);
    if (!hits.length) return;

    // Walk up the Object3D hierarchy to the root planet mesh (isPlanet=true)
    let obj = hits[0].object;
    while (obj && !obj.userData.isPlanet) obj = obj.parent;
    if (!obj?.userData?.isPlanet) return;

    const planet = planetObjects.find(p => p.data.name === obj.userData.name);
    if (planet) { showPlanetInfo(planet.data); startFocusFlyby(planet); }
  }

  renderer.domElement.addEventListener('pointerdown', onPointerDown);

  // ── Resize Handler ─────────────────────────────────────────────
  function onResize() {
    const w = containerElement.clientWidth, h = containerElement.clientHeight;
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    renderer.setSize(w, h);
  }
  window.addEventListener('resize', onResize);

  // ── Animation Loop ─────────────────────────────────────────────
  let animId = null;
  const clock = new THREE.Clock();

  function animate() {
    animId = requestAnimationFrame(animate);

    // Clamp delta to 50 ms — prevents huge jumps when tab loses focus
    const delta = Math.min(clock.getDelta(), 0.05);
    const dt    = delta * simSpeed; // simulation-speed-scaled delta

    // Sun self-rotation
    sun.rotation.y += 0.0018 * Math.max(simSpeed, 0.001);

    // ── Planet orbital & axial motion ──────────────────────────
    planetObjects.forEach(({ data, pivot, mesh }) => {
      /**
       * Orbital angular velocity:  ω = (v / r) × scale
       *
       * data.orbitSpeed represents scaled linear orbital speed (km/s analogue).
       * Dividing by orbitRadius converts linear speed to angular velocity so
       * outer planets complete fewer full orbits per unit time, approximating
       * Kepler's 3rd law:  T ∝ r^(3/2)  →  ω ∝ r^(-3/2).
       * The constant 5.5 sets a comfortable overall viewing speed.
       */
      pivot.rotation.y += (data.orbitSpeed / data.orbitRadius) * dt * 5.5;

      // Axial self-rotation — independent of orbital mechanics
      mesh.rotation.y += data.rotationSpeed * Math.max(simSpeed, 0.001);

      // Cloud shells orbit slightly faster than the surface below them
      mesh.children.forEach(child => {
        if (child.userData.isCloud)
          child.rotation.y += data.rotationSpeed * 0.35 * Math.max(simSpeed, 0.001);
      });
    });

    // ── Camera focus / return interpolation ────────────────────
    /**
     * Camera motion uses raw delta (not dt) so the flyby speed
     * remains comfortable regardless of the simulation speed setting.
     */
    if (isFocusing) {
      focusProgress = Math.min(focusProgress + delta * 0.72, 1);
      const t = easeInOutCubic(focusProgress);

      let toPos, toTgt;
      if (focusTarget) {
        // Get the planet's current world-space centre
        const wp = new THREE.Vector3();
        focusTarget.mesh.getWorldPosition(wp);
        // Hover beside and slightly above — offset scales with planet size
        const dist = focusTarget.data.radius * 5.5 + 10;
        toPos = new THREE.Vector3(wp.x + dist * 0.8, wp.y + dist * 0.4, wp.z + dist * 0.8);
        toTgt = wp.clone();
      } else {
        toPos = OVERVIEW_POS.clone();
        toTgt = OVERVIEW_TGT.clone();
      }

      camera.position.lerpVectors(camFrom, toPos, t);
      controls.target.lerpVectors(tgtFrom, toTgt, t);

      if (focusProgress >= 1) {
        isFocusing = false;
        controls.enabled = true;
      }
    }

    // Subtle starfield drift for added parallax depth
    starfield.rotation.y += 0.000042;

    controls.update(); // required every frame when enableDamping=true
    renderer.render(scene, camera);
  }

  animate();

  // ═══════════════════════════════════════════════════════════════
  //  CLEANUP FUNCTION — returned for React useEffect
  //
  //  React calls this when the component unmounts. It must:
  //
  //  1. Cancel the requestAnimationFrame loop so we stop rendering
  //     to a detached or reused canvas element.
  //
  //  2. Remove every DOM event listener attached by this function
  //     to prevent ghost listeners accumulating across hot-reloads.
  //
  //  3. Dispose all Three.js GPU-side objects: geometries, materials,
  //     and textures.  Not doing this leaks WebGL memory and can
  //     exhaust the GPU context after many mount/unmount cycles.
  //
  //  4. Dispose OrbitControls, which internally attaches its own
  //     pointer, wheel, and keyboard listeners to the canvas.
  //
  //  5. Dispose the WebGLRenderer and remove its <canvas> from the
  //     container DOM node.
  //
  //  6. Remove the HTML overlay elements this function injected
  //     into containerElement.
  // ═══════════════════════════════════════════════════════════════
  function cleanup() {
    // 1. Stop render loop
    if (animId !== null) cancelAnimationFrame(animId);

    // 2. Remove event listeners
    renderer.domElement.removeEventListener('pointerdown', onPointerDown);
    window.removeEventListener('resize', onResize);

    // 3. Dispose tracked resources (geometries, materials, textures)
    disposables.forEach(item => item?.dispose?.());

    // 4. Deep-traverse scene for anything not in the disposables array
    //    (Sun corona shells, embedded wireframe children, ring meshes, etc.)
    scene.traverse((obj) => {
      if (!obj.isMesh) return;
      obj.geometry?.dispose();
      const mats = Array.isArray(obj.material) ? obj.material : [obj.material];
      mats.forEach(m => {
        if (!m) return;
        // Dispose every texture channel present on the material
        Object.values(m).forEach(val => {
          if (val instanceof THREE.Texture) val.dispose();
        });
        m.dispose();
      });
    });

    // 5. Dispose OrbitControls (removes its internal DOM listeners)
    controls.dispose();

    // 6. Dispose renderer and detach canvas
    renderer.dispose();
    if (renderer.domElement.parentNode === containerElement) {
      containerElement.removeChild(renderer.domElement);
    }

    // 7. Remove UI overlay elements appended by this function
    [overlay, speedHud].forEach(el => {
      if (el?.parentNode === containerElement) containerElement.removeChild(el);
    });
  }

  return cleanup;
}